name: Update gist
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: extremecodetv/youtube-box@master
        env:
          GIST_ID: d17343f3b81f94b74abb36bd83e2b7ff
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_CHANNEL_ID: UCBNlINWfd08qgDkUTaUY4_w
