name: youtube-box
on:
  schedule:
    - cron: '0 * * * *'  # hourly
  push:
    branches: master
jobs:
  musicbox:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: npm install
     - name: Update
       uses: ./
       env:
        GIST_ID: d17343f3b81f94b74abb36bd83e2b7ff
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        YOUTUBE_CHANNEL_ID: UCBNlINWfd08qgDkUTaUY4_w
